### ISSUE TITLE
Beralih ke strapi ni

### ISSUE THREAD

**Issue by Aslam97** [sinardyas/cobain-strapi-simple-commerce#1]

**Comment by sinardyas** [comment]
njir ada issue wkwk
coba coba dulu cuuuy keren juga nih bisa typescript, tapi lebi mantep frappe si secara fitur

**Comment by Aslam97** [comment]
@sinardyas Kalau kamu merasa typescript itu keren. coba lihat PR ini https://github.com/hotwired/turbo/pull/971 wkwkwk

**Comment by sinardyas** [comment]
buset tuh orang punya masalah ape sama typescript wkwkwk, same fully di takeout
